#ifndef PC_PACKAGE_TYPE_H
#define PC_PACKAGE_TYPE_H

#include <cinttypes>

typedef uint16_t PackageTypeInt;

enum class PC_PackageType : PackageTypeInt {
    // RESERVED (0 - 9)
    NONE = 0,

    // DEVICE PAIRING (10 - 99)
    PAIR_REQUEST = 10,
    PAIR_REQUEST_DENIED = 11,
    PAIR_REQUEST_ACCEPTED = 12,

    // NETWORK CAMERA MODULE (1000-1499)
    NETWORK_CAMERA_MODULE_REQUEST_REMOTE_KEY = 1000,
    NETWORK_CAMERA_MODULE_REQUEST_REMOTE_KEY_RESPONSE = 1001,
    NETWORK_CAMERA_MODULE_REQUEST_CAMERAS_SPECIFICATION_LIST = 1002,
    NETWORK_CAMERA_MODULE_REQUEST_CAMERAS_SPECIFICATION_LIST_RESPONSE = 1003,
    NETWORK_CAMERA_MODULE_REQUEST_CAMERA_SWITCH = 1004,
    NETWORK_CAMERA_MODULE_REQUEST_CAMERA_SWITCH_RESPONSE = 1005,
    NETWORK_CAMERA_MODULE_REQUEST_START_STREAM = 1006,
    NETWORK_CAMERA_MODULE_REQUEST_START_STREAM_RESPONSE = 1007,
    NETWORK_CAMERA_MODULE_REQUEST_STOP_STREAM = 1008,

    // FILE SHARE MODULE (1500 - 1999)
    CONNECTION_CHANNEL_CONNECTION_PORT_INFO = 1500,
    FILE_SHARE_MODULE_ENABLE = 1501,
    FILE_SHARE_MODULE_DISABLE = 1502,
    FILE_SHARE_DIRECTORY_ENTRIES_REQUEST = 1503,
    FILE_SHARE_DIRECTORY_ENTRIES_RESPONSE = 1504,

};

#endif //PC_PACKAGE_TYPE_H