buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.22"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    compileSdk 34
    namespace "com.LibreConnect.mobile"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

    defaultConfig {
        applicationId "com.LibreConnect.mobile"
        minSdkVersion 28
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
            pickFirsts += ['**/libc++_shared.so']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.lifecycle:lifecycle-service:2.6.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
}
