function(load_env_file filepath)
    file(READ "${filepath}" content)
    string(REGEX REPLACE "\r?\n" ";" lines "${content}")
    foreach(line IN LISTS lines)
        string(STRIP "${line}" line)
        if(line MATCHES "^[^#].*=.*")
            string(REGEX MATCH "([^=]+)=(.*)" _ "${line}")
            set(key "${CMAKE_MATCH_1}")
            set(value "${CMAKE_MATCH_2}")
            set(ENV{${key}} "${value}")
        endif()
    endforeach()
endfunction()