name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml

  build-ubuntu:
    uses: ./.github/workflows/build-ubuntu.yml

  build-ubuntu-arm:
    uses: ./.github/workflows/build-ubuntu-arm.yml

  build-fedora-installer:
    needs:
      - build-ubuntu
    uses: ./.github/workflows/build-fedora-installer.yml

  build-macos:
    uses: ./.github/workflows/build-macos.yml

  build-android-armv8:
    uses: ./.github/workflows/build-android-armv8.yml
    secrets: inherit
